#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace gamestream {

// ---------------------------------------------------------------------------
// Session Description (SDP)
// ---------------------------------------------------------------------------

/// Type of a WebRTC Session Description Protocol message.
///
/// Maps 1:1 to webrtc::SdpType in libwebrtc so that conversion is trivial.
enum class SessionDescriptionType {
    kOffer,     ///< Initiator sends an offer containing codec/ICE parameters.
    kPrAnswer,  ///< Provisional answer before final negotiation.
    kAnswer,    ///< Responder confirms the offer.
    kRollback,  ///< Reverts local description to the previous stable state.
};

/// Returns a human-readable string for logging ("offer", "pranswer", "answer", "rollback").
[[nodiscard]] inline const char* to_string(SessionDescriptionType t) noexcept {
    switch (t) {
        case SessionDescriptionType::kOffer:    return "offer";
        case SessionDescriptionType::kPrAnswer: return "pranswer";
        case SessionDescriptionType::kAnswer:   return "answer";
        case SessionDescriptionType::kRollback: return "rollback";
    }
    return "unknown";
}

/// An SDP document exchanged via the signaling channel.
struct SessionDescription {
    SessionDescriptionType type;
    std::string            sdp;

    bool operator==(const SessionDescription& other) const noexcept {
        return type == other.type && sdp == other.sdp;
    }
    bool operator!=(const SessionDescription& other) const noexcept {
        return !(*this == other);
    }
};

// ---------------------------------------------------------------------------
// ICE Candidate
// ---------------------------------------------------------------------------

/// A single ICE candidate generated by the local ICE agent.
struct IceCandidateInfo {
    std::string sdp_mid;         ///< Media stream identification tag (e.g., "video")
    int         sdp_mline_index; ///< Index of the m= line in the SDP
    std::string sdp;             ///< The candidate attribute string (a=candidate:...)

    bool operator==(const IceCandidateInfo& other) const noexcept {
        return sdp_mid         == other.sdp_mid
            && sdp_mline_index == other.sdp_mline_index
            && sdp             == other.sdp;
    }
    bool operator!=(const IceCandidateInfo& other) const noexcept {
        return !(*this == other);
    }
};

// ---------------------------------------------------------------------------
// Connection states
// ---------------------------------------------------------------------------

/// Overall PeerConnection state (mirrors RTCPeerConnectionState in the browser).
enum class PeerConnectionState {
    kNew,           ///< PeerConnection created, no ICE activity yet.
    kConnecting,    ///< ICE negotiation in progress.
    kConnected,     ///< All ICE transports are connected or completed.
    kDisconnected,  ///< At least one transport disconnected (may self-recover).
    kFailed,        ///< ICE failed; connection cannot be established.
    kClosed,        ///< close() was called or the remote side closed the connection.
};

[[nodiscard]] inline const char* to_string(PeerConnectionState s) noexcept {
    switch (s) {
        case PeerConnectionState::kNew:          return "new";
        case PeerConnectionState::kConnecting:   return "connecting";
        case PeerConnectionState::kConnected:    return "connected";
        case PeerConnectionState::kDisconnected: return "disconnected";
        case PeerConnectionState::kFailed:       return "failed";
        case PeerConnectionState::kClosed:       return "closed";
    }
    return "unknown";
}

/// ICE connection state.
enum class IceConnectionState {
    kNew,
    kChecking,
    kConnected,
    kCompleted,
    kFailed,
    kDisconnected,
    kClosed,
};

[[nodiscard]] inline const char* to_string(IceConnectionState s) noexcept {
    switch (s) {
        case IceConnectionState::kNew:          return "new";
        case IceConnectionState::kChecking:     return "checking";
        case IceConnectionState::kConnected:    return "connected";
        case IceConnectionState::kCompleted:    return "completed";
        case IceConnectionState::kFailed:       return "failed";
        case IceConnectionState::kDisconnected: return "disconnected";
        case IceConnectionState::kClosed:       return "closed";
    }
    return "unknown";
}

/// SDP signaling state.
enum class SignalingState {
    kStable,
    kHaveLocalOffer,
    kHaveLocalPrAnswer,
    kHaveRemoteOffer,
    kHaveRemotePrAnswer,
    kClosed,
};

[[nodiscard]] inline const char* to_string(SignalingState s) noexcept {
    switch (s) {
        case SignalingState::kStable:             return "stable";
        case SignalingState::kHaveLocalOffer:     return "have-local-offer";
        case SignalingState::kHaveLocalPrAnswer:  return "have-local-pranswer";
        case SignalingState::kHaveRemoteOffer:    return "have-remote-offer";
        case SignalingState::kHaveRemotePrAnswer: return "have-remote-pranswer";
        case SignalingState::kClosed:             return "closed";
    }
    return "unknown";
}

// ---------------------------------------------------------------------------
// Signaling message
// ---------------------------------------------------------------------------

/// Type tag for messages exchanged on the signaling channel.
enum class SignalingMessageType {
    kSdp,
    kIceCandidate,
};

/// A single message sent/received on the signaling WebSocket.
struct SignalingMessage {
    SignalingMessageType type;
    SessionDescription   sdp;       ///< Valid when type == kSdp
    IceCandidateInfo     candidate; ///< Valid when type == kIceCandidate
};

// ---------------------------------------------------------------------------
// WebRTC host configuration
// ---------------------------------------------------------------------------

/// STUN/TURN server entry.
struct IceServer {
    std::string uri;
    std::string username;
    std::string password;
};

/// Configuration passed to IWebRTCHost::initialize().
struct WebRTCConfig {
    std::vector<IceServer> ice_servers;
    std::string input_channel_label = "input";
    int         ice_backup_candidate_pair_ping_interval_ms = 1000;
    int         ice_connection_receiving_timeout_ms = 10000;
};

} // namespace gamestream
